version: '3'

services:
  wp:
    image: wordpress:4.9-php7.0-apache
    volumes:
      - ./:/var/www/html/wp-content
    ports:
      - "80:80"
    links:
      - database
    environment:
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_HOST: "database"
      WORDPRESS_DB_USER: "root"
    logging:
      options:
        max-size: "10k"

  database:
    image: mysql:5.5
    volumes:
      - ./db_dump:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: wordpress
    logging:
      options:
        max-size: "5k"

  pma:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_USER: "root"
    ports:
      - "81:80"

volumes:
  db_data: